services:
  portfolio:
    build:
      context: .
      dockerfile: dockerfile
    container_name: portfolio
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3000
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      NEXT_PUBLIC_WEB3FORMS_ACCESS_KEY: ${NEXT_PUBLIC_WEB3FORMS_ACCESS_KEY}
    networks:
      proxy-net:
        aliases:
          - portfolio

networks:
  proxy-net:
    external: true